namespace: demo-prod
resources:
- namespace.yaml
- pipeline-rolebinding.yaml
- github.com/gnunn-gitops/product-catalog/components/apps/database/base
- github.com/gnunn-gitops/product-catalog/components/apps/client/base
- github.com/gnunn-gitops/product-catalog/components/apps/server/base
images:
- name: quay.io/gnunn/server
  newName: quay.io/gnunn/server2
  digest: sha256:c391c7eca7bd11b9af2b703859bb30ab7c06fac66a2c4712e52feda3ad59fcab
